name: lint, check format and run build for test

on:
  push:
    branches: [main, dev]
    pull_request:
      branches: [main, dev]

permissions:
  contents: read

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Build
        run: deno task build
