name: attach build artifact to release manually

on: workflow_dispatch

env:
  TEMP_ASSET_NAME: asset.zip

jobs:
  attach-build-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ toJson(github) }}"

      - name: Extract tag from ref
        env:
          REF: ${{ github.ref }}
        run: |
          [[ $REF =~ ^refs/tags/ ]] || exit 1
          TAG_NAME=$(echo $REF | sed -E s#^refs/tags/##)
          echo "TAG_NAME=$TAG_NAME" >> GITHUB_ENV

      - name: Get upload url
        env:
          RELEASES_URL: ${{ github.event.repository.releases_url }}
        run: |
          URL=$(echo "$RELEASES_URL" | sed -e s:{/id}:/tags/$TAG_NAME:)
          JSON_TEXT=$(curl -sSL $URL)
          UPLOAD_URL=$(echo "$JSON_TEXT" | jq ".upload_url")
          echo "UPLOAD_URL=$UPLOAD_URL" >> GITHUB_ENV

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno task build

      - name: Create zip
        run: cd ./dist; zip $TEMP_ASSET_NAME -r .

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./dist/${{ env.TEMP_ASSET_NAME }}
          asset_name: nitech-moodle-extension-40a-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip
